language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
before_script:
  - sleep 15
  - sh ./scripts/travisScript.sh
script:
  - npm test
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage